size: 5
max: 50
default_password: 1
per_page: 5
exam_per_page: 10
time_format: "%H:%M:%S"
day_format: "%Y/%m/%d %H:%M:%S"
boolean:
  false: false
  true: true
mail: "dat.hedspi@gmail.com"
approve: "approve"
reject: "reject"
wait: "wait"
